KEY=${DIRECTUS_KEY}
SECRET=${DIRECTUS_SECRET}

ADMIN_EMAIL=${DIRECTUS_ADMIN_EMAIL}
ADMIN_PASSWORD=${DIRECTUS_ADMIN_PASSWORD}

DB_CLIENT=pg
DB_HOST=aegora-postgres
DB_PORT=5432
DB_DATABASE=${POSTGRES_DIRECTUS_DB}
DB_USER=${POSTGRES_DIRECTUS_USER}
DB_PASSWORD=${POSTGRES_DIRECTUS_PASSWORD}

PUBLIC_URL=https://${DIRECTUS_HOST}

WEBSOCKETS_ENABLED=true

TELEMETRY=false

LOG_LEVEL=info
