DB_TYPE=postgresdb
DB_POSTGRESDB_HOST=aegora-postgres
DB_POSTGRESDB_PORT=5432
DB_POSTGRESDB_DATABASE=${POSTGRES_N8N_DB}
DB_POSTGRESDB_USER=${POSTGRES_N8N_USER}
DB_POSTGRESDB_PASSWORD=${POSTGRES_N8N_PASSWORD}
DB_POSTGRESDB_SCHEMA=public

N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}

N8N_HOST=${N8N_HOST}
N8N_PORT=5678
N8N_PROTOCOL=https

N8N_EDITOR_BASE_URL=https://${N8N_HOST}
N8N_WEBHOOK_URL=https://${N8N_HOST}/

N8N_PROXY_HOPS=1

GENERIC_TIMEZONE=Europe/Madrid
TZ=Europe/Madrid

# Booking API interno del tenant (lo consume el workflow APPOINTMENT Availability).
# El token va en una credencial n8n "Booking API" (Header Auth), no aquí.
BOOKING_API_BASE_URL=http://${BOOKING_CONTAINER}:3000

NODE_ENV=production

N8N_LOG_LEVEL=info
N8N_DIAGNOSTICS_ENABLED=false
N8N_PERSONALIZATION_ENABLED=false
N8N_TEMPLATES_ENABLED=false

N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
N8N_SECURE_COOKIE=true

N8N_UNVERIFIED_PACKAGES_ENABLED=false

EXECUTIONS_MODE=regular
EXECUTIONS_DATA_PRUNE=true
EXECUTIONS_DATA_MAX_AGE=336
EXECUTIONS_DATA_PRUNE_MAX_COUNT=10000

N8N_DEFAULT_BINARY_DATA_MODE=filesystem

N8N_RUNNERS_TASK_TIMEOUT=300
N8N_COMPRESSION_NODE_MAX_DECOMPRESSED_SIZE_BYTES=268435456
N8N_COMPRESSION_NODE_MAX_ZIP_ENTRIES=1000
